/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.NGOSupervisorRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.BillingOrganization;
import Business.Organization.DoctorOrganization;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.BillingWorkQueue;
import Business.WorkQueue.DoctorWorkRequest;
import Business.WorkQueue.NGOWorkRequest;
import Business.email.Email;
import java.awt.CardLayout;
import java.awt.Component;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.FileHandler;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.logging.SimpleFormatter;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import userinterface.PoliceRole.PoliceViewRecordJPanel;

/**
 *
 * @author raunak
 */
public class ProcessNGORequestJPanel extends javax.swing.JPanel {

    
    
    JPanel userProcessContainer;
    private Enterprise enterprise;
    private UserAccount userAccount;
    private NGOWorkRequest request;
    private EcoSystem business;
    //private Network network;
    
    public ProcessNGORequestJPanel(JPanel userProcessContainer, NGOWorkRequest request, Enterprise enterprise, UserAccount userAccount, Network network, EcoSystem business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.request = request;
        this.enterprise = enterprise;
        this.userAccount = userAccount;
        this.business = business;
        showResult();
        submitJButton.setToolTipText("Send the Person's details to Doctor");
        //this.network = network;
        
         //  jTextField1.setText(request.getFoodCost());
    }
    
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        submitJButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        resultJTextField = new javax.swing.JTextField();
        backJButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        idTxt = new javax.swing.JTextField();
        nameTxt = new javax.swing.JTextField();
        ageTxt = new javax.swing.JTextField();
        locationTxt = new javax.swing.JTextField();
        gendertxt = new javax.swing.JTextField();
        clothTxt = new javax.swing.JTextField();
        treatmentTxt = new javax.swing.JTextField();
        foodTxt = new javax.swing.JTextField();
        criminalTxt = new javax.swing.JTextField();
        btnBilling = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(null);

        submitJButton.setBackground(new java.awt.Color(0, 0, 0));
        submitJButton.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        submitJButton.setForeground(new java.awt.Color(255, 255, 255));
        submitJButton.setText("Send To Doctor");
        submitJButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 4));
        submitJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitJButtonActionPerformed(evt);
            }
        });
        add(submitJButton);
        submitJButton.setBounds(1190, 680, 210, 40);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Result");
        add(jLabel1);
        jLabel1.setBounds(1250, 580, 90, 22);

        resultJTextField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        add(resultJTextField);
        resultJTextField.setBounds(1450, 580, 113, 28);

        backJButton.setBackground(new java.awt.Color(0, 0, 0));
        backJButton.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        backJButton.setForeground(new java.awt.Color(255, 255, 255));
        backJButton.setText("Back");
        backJButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 4));
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton);
        backJButton.setBounds(1020, 110, 70, 40);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Name");
        add(jLabel2);
        jLabel2.setBounds(1250, 260, 100, 26);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("ID");
        add(jLabel3);
        jLabel3.setBounds(1250, 220, 100, 26);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Age");
        add(jLabel4);
        jLabel4.setBounds(1250, 300, 100, 26);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Gender");
        add(jLabel5);
        jLabel5.setBounds(1250, 380, 100, 26);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Location");
        add(jLabel6);
        jLabel6.setBounds(1250, 340, 100, 26);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Treatment Required?");
        add(jLabel7);
        jLabel7.setBounds(1250, 460, 230, 26);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("Clothing Required?");
        add(jLabel8);
        jLabel8.setBounds(1250, 420, 210, 26);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setText("Food Required?");
        add(jLabel9);
        jLabel9.setBounds(1250, 500, 180, 26);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setText("Is Criminal?");
        add(jLabel10);
        jLabel10.setBounds(1250, 540, 180, 26);

        idTxt.setEditable(false);
        idTxt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        idTxt.setEnabled(false);
        add(idTxt);
        idTxt.setBounds(1450, 220, 113, 28);

        nameTxt.setEditable(false);
        nameTxt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        nameTxt.setEnabled(false);
        add(nameTxt);
        nameTxt.setBounds(1450, 260, 113, 28);

        ageTxt.setEditable(false);
        ageTxt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ageTxt.setEnabled(false);
        add(ageTxt);
        ageTxt.setBounds(1450, 300, 113, 28);

        locationTxt.setEditable(false);
        locationTxt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        locationTxt.setEnabled(false);
        add(locationTxt);
        locationTxt.setBounds(1450, 340, 113, 28);

        gendertxt.setEditable(false);
        gendertxt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        gendertxt.setEnabled(false);
        add(gendertxt);
        gendertxt.setBounds(1450, 380, 113, 28);

        clothTxt.setEditable(false);
        clothTxt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        clothTxt.setEnabled(false);
        add(clothTxt);
        clothTxt.setBounds(1450, 420, 113, 28);

        treatmentTxt.setEditable(false);
        treatmentTxt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        treatmentTxt.setEnabled(false);
        add(treatmentTxt);
        treatmentTxt.setBounds(1450, 460, 113, 28);

        foodTxt.setEditable(false);
        foodTxt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        foodTxt.setEnabled(false);
        add(foodTxt);
        foodTxt.setBounds(1450, 500, 113, 28);

        criminalTxt.setEditable(false);
        criminalTxt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        criminalTxt.setEnabled(false);
        add(criminalTxt);
        criminalTxt.setBounds(1450, 540, 113, 28);

        btnBilling.setBackground(new java.awt.Color(0, 0, 0));
        btnBilling.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnBilling.setForeground(new java.awt.Color(255, 255, 255));
        btnBilling.setText("Sent To Billing");
        btnBilling.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 4));
        btnBilling.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBillingActionPerformed(evt);
            }
        });
        add(btnBilling);
        btnBilling.setBounds(1480, 680, 180, 40);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("NGO Work Area");
        jLabel11.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 13), new java.awt.Color(102, 102, 102))); // NOI18N
        add(jLabel11);
        jLabel11.setBounds(0, 0, 1750, 80);

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel13.setIcon(new javax.swing.ImageIcon("C:\\Users\\rachi\\Desktop\\Images Project\\ngowork.jpg")); // NOI18N
        jLabel13.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel13.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel13.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        add(jLabel13);
        jLabel13.setBounds(0, 80, 980, 860);

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("jLabel3");
        jLabel12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 6));
        add(jLabel12);
        jLabel12.setBounds(980, 80, 770, 860);
    }// </editor-fold>//GEN-END:initComponents

    
    
    
    private void showResult()
    {
        idTxt.setText(request.getId());
        nameTxt.setText(request.getName1());
        ageTxt.setText(String.valueOf(request.getAge()));
        locationTxt.setText(request.getLocation());
        gendertxt.setText(request.getGender());
        
        
        if(request.getCloth())
        clothTxt.setText("No");
        else
              clothTxt.setText("Provided");

         if(request.getFood())
        foodTxt.setText("No");
        else
              foodTxt.setText("Provided");
         
        if(request.getTreatment())
        {
        treatmentTxt.setText("Yes");
        
        submitJButton.setEnabled(true);
        btnBilling.setEnabled(false);
        
        }
        else
        {
              treatmentTxt.setText("No");
              
              
              submitJButton.setEnabled(false);
        btnBilling.setEnabled(true);
        
        }
        if(request.getCriminal())
        criminalTxt.setText("Yes");
        else
              criminalTxt.setText("No");
        
        
        
        
        
    }
    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed

        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        NGOSupervisorWorkAreaJPanel dwjp = (NGOSupervisorWorkAreaJPanel) component;
        dwjp.populateTable();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void submitJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitJButtonActionPerformed
        
        
        String message = resultJTextField.getText();
        
        
         if(message==null||message.equals("")){
       JOptionPane.showMessageDialog(null, "Enter Request Message");
       return;
       }
        
        DoctorWorkRequest doctorRequest = new DoctorWorkRequest();
        
        doctorRequest.setMessage(message);
        doctorRequest.setId(idTxt.getText());
        doctorRequest.setSender(userAccount);
        doctorRequest.setTestResult(resultJTextField.getText());
        doctorRequest.setStatus("Sent to Doctor");
        doctorRequest.setName1(nameTxt.getText());
        doctorRequest.setAge(Integer.parseInt(ageTxt.getText()));
        doctorRequest.setLocation(locationTxt.getText());
        doctorRequest.setGender(gendertxt.getText());
        doctorRequest.setCloth(request.getCloth());
        doctorRequest.setFood(request.getFood());
        doctorRequest.setTreatment(request.getTreatment());
        doctorRequest.setCriminal(request.getCriminal());
        doctorRequest.setFoodCost(request.getFoodCost());
        doctorRequest.setClothCost(request.getClothCost());
        
        
        
        
        
Organization org = null;
        for(Network network : business.getNetworkList()){
           // if (enterprise instanceof HospitalEnterprise){
        for(Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()){
           
       
        for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()){
            if (organization instanceof DoctorOrganization){
                org = organization;
                break;
            }
        }
        
        if (org!=null){
            org.getWorkQueue().getWorkRequestList().add(doctorRequest);
            userAccount.getWorkQueue().getWorkRequestList().add(doctorRequest);
            break;
            //System.out.println(doctorRequest);
        }
        }
        //}
        }  
        
        request.setStatus("Sent to Doctor");
        
        
           try {
            Email.sendMail("pvidhi107@gmail.com","Treatment Required for "+request.getName1(),"Information of "+request.getName1()+"has been added to the queue for Treatment . Please take necessary action");
            
        } catch (Exception ex) {
            Logger.getLogger(PoliceViewRecordJPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
           
          JOptionPane.showMessageDialog(null, "Information Sent to Doctor");  
          
          
          Logger logger = Logger.getLogger("MyLog");  
      FileHandler fh;  

    try {  

        // This block configure the logger with handler and formatter  
        fh = new FileHandler("D:/MyLogFile.log");  
        logger.addHandler(fh);
        SimpleFormatter formatter = new SimpleFormatter();  
        fh.setFormatter(formatter);  

        // the following statement is used to log any messages  
        logger.info("Request for "+doctorRequest.getName1()+"has been sent to Doctor by "+userAccount);  

    } catch (SecurityException e) {  
        e.printStackTrace();  
    } catch (IOException e) {  
        e.printStackTrace();  
    } 
    }//GEN-LAST:event_submitJButtonActionPerformed

    private void btnBillingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBillingActionPerformed
        
          String message = resultJTextField.getText();
        
          
          
          
          if(message==null||message.equals("")){
       JOptionPane.showMessageDialog(null, "Enter Request Message");
       return;
       }
        BillingWorkQueue billingRequest = new BillingWorkQueue();
        
        billingRequest.setMessage(message);
        billingRequest.setId(request.getId());
        billingRequest.setSender(userAccount);
        billingRequest.setTestResult(resultJTextField.getText());
        billingRequest.setStatus("Sent to Billing");
        billingRequest.setName1(request.getName1());
        billingRequest.setAge(request.getAge());
        billingRequest.setLocation(request.getLocation());
        billingRequest.setGender(request.getGender());
        billingRequest.setCloth(request.getCloth());
        billingRequest.setFood(request.getFood());
        billingRequest.setTreatment(request.getTreatment());
        billingRequest.setCriminal(request.getCriminal());
        billingRequest.setFoodCost(request.getFoodCost());
        billingRequest.setClothCost(request.getClothCost());
        billingRequest.setLabbill(0);
        billingRequest.setDoctorbill(0);
        
        
        
        
       
    
        Organization org = null;
        for(Network network : business.getNetworkList()){
           // if (enterprise instanceof HospitalEnterprise){
        for(Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()){
           
       
        for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()){
            if (organization instanceof BillingOrganization){
                org = organization;
                break;
            }
        }
        
        if (org!=null){
            org.getWorkQueue().getWorkRequestList().add(billingRequest);
            userAccount.getWorkQueue().getWorkRequestList().add(billingRequest);
            break;
            //System.out.println(doctorRequest);
        }
        }
        //}
        }
        
        
           try {
                
            Email.sendMail("pvidhi107@gmail.com","Final Invoice for "+request.getName1()+" is ready ","Please find below the Doctor's Consulting fee for "+request.getName1()+": $"+resultJTextField.getText());
                
             
        } catch (Exception ex) {
            Logger.getLogger(PoliceViewRecordJPanel.class.getName()).log(Level.SEVERE, null, ex);
        }// TODO add your handling code here:
           
           
            JOptionPane.showMessageDialog(null, "Information Sent to Billing");  
            
            
            
            
Logger logger = Logger.getLogger("MyLog");  
      FileHandler fh;  

    try {  

        // This block configure the logger with handler and formatter  
        fh = new FileHandler("D:/MyLogFile.log");  
        logger.addHandler(fh);
        SimpleFormatter formatter = new SimpleFormatter();  
        fh.setFormatter(formatter);  

        // the following statement is used to log any messages  
        logger.info("Request for "+billingRequest.getName1()+"has been sent to Billing by "+userAccount);  

    } catch (SecurityException e) {  
        e.printStackTrace();  
    } catch (IOException e) {  
        e.printStackTrace();  
    } 
    
    
    }//GEN-LAST:event_btnBillingActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ageTxt;
    private javax.swing.JButton backJButton;
    private javax.swing.JButton btnBilling;
    private javax.swing.JTextField clothTxt;
    private javax.swing.JTextField criminalTxt;
    private javax.swing.JTextField foodTxt;
    private javax.swing.JTextField gendertxt;
    private javax.swing.JTextField idTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField locationTxt;
    private javax.swing.JTextField nameTxt;
    private javax.swing.JTextField resultJTextField;
    private javax.swing.JButton submitJButton;
    private javax.swing.JTextField treatmentTxt;
    // End of variables declaration//GEN-END:variables
}
