/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.LabArea;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.BillingOrganization;
import Business.Organization.LabOrganization;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.BillingWorkQueue;
import Business.WorkQueue.LabWorkRequest;
import Business.email.Email;
import java.awt.CardLayout;
import java.awt.Component;
import java.io.IOException;
import java.util.logging.FileHandler;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.logging.SimpleFormatter;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import userinterface.PoliceRole.PoliceViewRecordJPanel;

/**
 *
 * @author rachi
 */
public class SendLabResultJPanel extends javax.swing.JPanel {
    private JPanel userProcessContainer;
    private LabWorkRequest request;
    private UserAccount userAccount;
    private Network network;
    private EcoSystem business;
    /**
     * Creates new form SendLabResultJPanel
     */
    

    SendLabResultJPanel(JPanel userProcessContainer, LabWorkRequest request, Enterprise enterprise, UserAccount userAccount, Network network, EcoSystem business) {
         initComponents();
         this.userProcessContainer=userProcessContainer;
         this.request=request;
         this.userAccount=userAccount;
         this.network=network;
         this.business=business;
         
         submitJButton.setToolTipText("Publish the cost of Lab Test for Billing.");
         
         testTypeTxt.setText(request.getTesttype());
         
         
         
             if(testTypeTxt.getText().equals("Haemogram"))
                 costTxt.setText("50");
                else if(testTypeTxt.getText().equals("Ultra Sound"))
                    costTxt.setText("250");
                    else if(testTypeTxt.getText().equals("CT Scan"))
                        costTxt.setText("375");    
             else
                         costTxt.setText("0"); 
                        
         
             
         
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backJButton = new javax.swing.JButton();
        resultJTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        submitJButton = new javax.swing.JButton();
        testTypeTxt = new javax.swing.JTextField();
        costTxt = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setLayout(null);

        backJButton.setBackground(new java.awt.Color(0, 0, 0));
        backJButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        backJButton.setForeground(new java.awt.Color(255, 255, 255));
        backJButton.setText("Back");
        backJButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 4));
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton);
        backJButton.setBounds(40, 110, 116, 38);

        resultJTextField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        resultJTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        add(resultJTextField);
        resultJTextField.setBounds(820, 200, 180, 30);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Result");
        add(jLabel1);
        jLabel1.setBounds(610, 200, 75, 29);

        submitJButton.setBackground(new java.awt.Color(0, 0, 0));
        submitJButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        submitJButton.setForeground(new java.awt.Color(255, 255, 255));
        submitJButton.setText("Submit Result");
        submitJButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 4));
        submitJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitJButtonActionPerformed(evt);
            }
        });
        add(submitJButton);
        submitJButton.setBounds(700, 390, 131, 38);

        testTypeTxt.setEditable(false);
        testTypeTxt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        testTypeTxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        testTypeTxt.setEnabled(false);
        add(testTypeTxt);
        testTypeTxt.setBounds(820, 250, 180, 30);

        costTxt.setEditable(false);
        costTxt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        costTxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        costTxt.setEnabled(false);
        costTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                costTxtActionPerformed(evt);
            }
        });
        add(costTxt);
        costTxt.setBounds(820, 300, 180, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Lab Request ");
        jLabel8.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 13), new java.awt.Color(102, 102, 102))); // NOI18N
        add(jLabel8);
        jLabel8.setBounds(0, 0, 1750, 80);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setText("Test Type");
        add(jLabel4);
        jLabel4.setBounds(610, 250, 116, 29);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setText("Total Cost");
        add(jLabel5);
        jLabel5.setBounds(610, 300, 121, 29);

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\rachi\\Desktop\\Images Project\\labrequest.jpg")); // NOI18N
        jLabel2.setText("jLabel2");
        add(jLabel2);
        jLabel2.setBounds(0, 0, 1840, 890);
    }// </editor-fold>//GEN-END:initComponents

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed

        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        LabWorkAreaJPanel dwjp = (LabWorkAreaJPanel) component;
        dwjp.populateTable();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void submitJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitJButtonActionPerformed
            
        
        String message = resultJTextField.getText();
        
        
        
         if(message==null||message.equals("")){
       JOptionPane.showMessageDialog(null, "Enter some message");
       return;
       }

        
        BillingWorkQueue billingRequest = new BillingWorkQueue();
        
        billingRequest.setMessage(message);
        billingRequest.setId(request.getId());
        billingRequest.setSender(userAccount);
        billingRequest.setTestResult(resultJTextField.getText());
        billingRequest.setStatus("Sent to Billing");
        billingRequest.setName1(request.getName1());
        billingRequest.setAge(request.getAge());
        billingRequest.setLocation(request.getLocation());
        billingRequest.setGender(request.getGender());
        billingRequest.setCloth(request.getCloth());
        billingRequest.setFood(request.getFood());
        billingRequest.setTreatment(request.getTreatment());
        billingRequest.setCriminal(request.getCriminal());
        billingRequest.setFoodCost(request.getFoodCost());
        billingRequest.setClothCost(request.getClothCost());
        if(costTxt.getText().equals("0"))
        billingRequest.setLabbill(0);
        else
        billingRequest.setLabbill(Integer.parseInt(costTxt.getText()));
        
         billingRequest.setDoctorbill(request.getDoctorbill());
        
        
        
             
              
Organization org = null;
        for(Network network : business.getNetworkList()){
           // if (enterprise instanceof HospitalEnterprise){
        for(Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()){
           
       
        for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()){
            if (organization instanceof BillingOrganization){
                org = organization;
                break;
            }
        }
        
        if (org!=null){
            org.getWorkQueue().getWorkRequestList().add(billingRequest);
            userAccount.getWorkQueue().getWorkRequestList().add(billingRequest);
            break;
            //System.out.println(doctorRequest);
        }
        }
        //}
        }
        
        request.setTestResult(resultJTextField.getText());
        request.setStatus("Treatment Done");
        
        
           try {
                
            Email.sendMail("pvidhi107@gmail.com","Final Invoice for "+request.getName1()+" is ready ","Please find below the cost of "+request.getTesttype()+" for "+request.getName1()+": $");
                
             
        } catch (Exception ex) {
            Logger.getLogger(PoliceViewRecordJPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
           
           JOptionPane.showMessageDialog(null, "Sent to Billing");
           
           
           
           
           
Logger logger = Logger.getLogger("MyLog");  
      FileHandler fh;  

    try {  

        // This block configure the logger with handler and formatter  
        fh = new FileHandler("D:/MyLogFile.log");  
        logger.addHandler(fh);
        SimpleFormatter formatter = new SimpleFormatter();  
        fh.setFormatter(formatter);  

        // the following statement is used to log any messages  
        logger.info("Request for "+billingRequest.getName1()+"has been sent to Billing by "+userAccount);  

    } catch (SecurityException e) {  
        e.printStackTrace();  
    } catch (IOException e) {  
        e.printStackTrace();  
    } 

    }//GEN-LAST:event_submitJButtonActionPerformed

    private void costTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_costTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_costTxtActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JTextField costTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField resultJTextField;
    private javax.swing.JButton submitJButton;
    private javax.swing.JTextField testTypeTxt;
    // End of variables declaration//GEN-END:variables
}
