/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.DoctorRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Homeless.Homeless;
import Business.Homeless.HomelessDirectory;
import Business.Network.Network;
import Business.Organization.BillingOrganization;
import Business.Organization.DoctorOrganization;
import Business.Organization.LabOrganization;
import Business.Organization.NGOOrganization;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.BillingWorkQueue;
import Business.WorkQueue.DoctorWorkRequest;
import Business.WorkQueue.LabWorkRequest;
import Business.email.Email;
import java.awt.CardLayout;
import java.awt.Component;
import java.io.IOException;
import java.util.logging.FileHandler;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.logging.SimpleFormatter;
import javax.swing.JOptionPane;

import javax.swing.JPanel;
import userinterface.PoliceRole.PoliceViewRecordJPanel;

/**
 *
 * @author gloha
 */
public class DoctorPrescriptionJPanel extends javax.swing.JPanel {

    /**
     * Creates new form DoctroPrescriptionJPanel
     */
     private JPanel userProcessContainer;
    private DoctorOrganization doctorOrganization;
    private Enterprise enterprise;
    private UserAccount account;
    private HomelessDirectory homelessDirectory;
    private Homeless homeless;
    private EcoSystem business;
    private Network network;
    private DoctorWorkRequest request;

    DoctorPrescriptionJPanel(JPanel userProcessContainer, DoctorWorkRequest request, Enterprise enterprise, UserAccount account, Network network, EcoSystem business) {
        initComponents();
         this.userProcessContainer = userProcessContainer;
        this.account = account;
       this.request=request;
        this.enterprise = enterprise;
        this.business = business;
        this.homelessDirectory = new HomelessDirectory();
        showResult();
        
        
    }
    
    private void showResult()
    {
        jTextField1.setText(request.getName1());
        jTextField2.setText(String.valueOf(request.getAge()));
        jTextField3.setText(request.getGender());
        jComboBox1.addItem("Common Cold");
        jComboBox1.addItem("Viral Fever");
        jComboBox1.addItem("Internal Infection");
        jComboBox1.addItem("Organ Related Problem");
        jComboBox1.addItem("Chest Pain");
        jComboBox1.addItem("Headache");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        testRequiredTxt = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        messageTxt = new javax.swing.JTextArea();
        labBtn = new javax.swing.JButton();
        btnPharmacy = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        enterpriseLabel3 = new javax.swing.JLabel();
        enterpriseLabel4 = new javax.swing.JLabel();
        enterpriseLabel5 = new javax.swing.JLabel();
        enterpriseLabel6 = new javax.swing.JLabel();
        enterpriseLabel8 = new javax.swing.JLabel();
        enterpriseLabel9 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(null);

        jTextField1.setEditable(false);
        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        jTextField1.setEnabled(false);
        add(jTextField1);
        jTextField1.setBounds(880, 170, 190, 40);

        jTextField2.setEditable(false);
        jTextField2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        jTextField2.setEnabled(false);
        add(jTextField2);
        jTextField2.setBounds(880, 230, 190, 40);

        jTextField3.setEditable(false);
        jTextField3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        jTextField3.setEnabled(false);
        add(jTextField3);
        jTextField3.setBounds(880, 290, 190, 40);

        jComboBox1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jComboBox1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        add(jComboBox1);
        jComboBox1.setBounds(880, 340, 190, 40);

        testRequiredTxt.setEditable(false);
        testRequiredTxt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        testRequiredTxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        testRequiredTxt.setEnabled(false);
        testRequiredTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                testRequiredTxtActionPerformed(evt);
            }
        });
        add(testRequiredTxt);
        testRequiredTxt.setBounds(880, 390, 190, 40);

        messageTxt.setColumns(20);
        messageTxt.setRows(5);
        jScrollPane1.setViewportView(messageTxt);

        add(jScrollPane1);
        jScrollPane1.setBounds(880, 450, 250, 70);

        labBtn.setBackground(new java.awt.Color(0, 0, 0));
        labBtn.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        labBtn.setForeground(new java.awt.Color(255, 255, 255));
        labBtn.setText("Send To Lab");
        labBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 4));
        labBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                labBtnActionPerformed(evt);
            }
        });
        add(labBtn);
        labBtn.setBounds(650, 590, 160, 50);

        btnPharmacy.setBackground(new java.awt.Color(0, 0, 0));
        btnPharmacy.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnPharmacy.setForeground(new java.awt.Color(255, 255, 255));
        btnPharmacy.setText("Send To Billing");
        btnPharmacy.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 4));
        btnPharmacy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPharmacyActionPerformed(evt);
            }
        });
        add(btnPharmacy);
        btnPharmacy.setBounds(920, 590, 190, 50);

        jButton3.setBackground(new java.awt.Color(0, 0, 0));
        jButton3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Back");
        jButton3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 4));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        add(jButton3);
        jButton3.setBounds(810, 710, 140, 50);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Provide Prescription");
        jLabel8.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 13), new java.awt.Color(102, 102, 102))); // NOI18N
        add(jLabel8);
        jLabel8.setBounds(0, 0, 1750, 80);

        enterpriseLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        enterpriseLabel3.setText("Prescription");
        add(enterpriseLabel3);
        enterpriseLabel3.setBounds(670, 460, 170, 30);

        enterpriseLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        enterpriseLabel4.setText("Name");
        add(enterpriseLabel4);
        enterpriseLabel4.setBounds(670, 170, 170, 30);

        enterpriseLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        enterpriseLabel5.setText("Age");
        add(enterpriseLabel5);
        enterpriseLabel5.setBounds(670, 230, 170, 30);

        enterpriseLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        enterpriseLabel6.setText("Gender");
        add(enterpriseLabel6);
        enterpriseLabel6.setBounds(670, 290, 170, 30);

        enterpriseLabel8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        enterpriseLabel8.setText("Illness");
        add(enterpriseLabel8);
        enterpriseLabel8.setBounds(670, 340, 170, 30);

        enterpriseLabel9.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        enterpriseLabel9.setText("Test Required");
        add(enterpriseLabel9);
        enterpriseLabel9.setBounds(670, 390, 170, 30);

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\rachi\\Desktop\\Images Project\\prescribe.jpeg")); // NOI18N
        jLabel2.setText("jLabel2");
        add(jLabel2);
        jLabel2.setBounds(0, 0, 1750, 900);
    }// </editor-fold>//GEN-END:initComponents

    private void testRequiredTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_testRequiredTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_testRequiredTxtActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        
        int i = jComboBox1.getSelectedIndex();
        if (i==0)
        {
           testRequiredTxt.setText("No test Required");
           
           labBtn.setEnabled(false);
           btnPharmacy.setEnabled(true);
           
        }
        else if (i==1)
        {
           testRequiredTxt.setText("Haemogram");
           labBtn.setEnabled(true);
           btnPharmacy.setEnabled(false);
           
        }
        else if (i==2)
        {
           testRequiredTxt.setText("Ultra Sound");
           labBtn.setEnabled(true);
           btnPharmacy.setEnabled(false);
           
        }
        else if (i==3)
        {
           testRequiredTxt.setText("CT Scan");
           labBtn.setEnabled(true);
           btnPharmacy.setEnabled(false);
           
        }
        else if (i==4)
        {
           testRequiredTxt.setText("Ultra Sound");
           labBtn.setEnabled(true);
           btnPharmacy.setEnabled(false);
           
        }
        else if (i==5)
        {
           testRequiredTxt.setText("No test Required");
           labBtn.setEnabled(false);
           btnPharmacy.setEnabled(true);
           
        }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void btnPharmacyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPharmacyActionPerformed
        // TODO add your handling code here:
        
        
        
        
          String message = messageTxt.getText();
          
        
         if(message==null||message.equals("")){
       JOptionPane.showMessageDialog(null, "Enter Prescription");
       return;
       }

        
        BillingWorkQueue billingRequest = new BillingWorkQueue();
        
        billingRequest.setMessage(message);
        billingRequest.setId(request.getId());
        billingRequest.setSender(account);
        billingRequest.setTestResult(messageTxt.getText());
        billingRequest.setStatus("Sent to Billing");
        billingRequest.setName1(request.getName1());
        billingRequest.setAge(request.getAge());
        billingRequest.setLocation(request.getLocation());
        billingRequest.setGender(request.getGender());
        billingRequest.setCloth(request.getCloth());
        billingRequest.setFood(request.getFood());
        billingRequest.setTreatment(request.getTreatment());
        billingRequest.setCriminal(request.getCriminal());
        billingRequest.setFoodCost(request.getFoodCost());
        billingRequest.setClothCost(request.getClothCost());
        billingRequest.setLabbill(0);
        
        
        if(testRequiredTxt.getText().equals("No test Required"))
             billingRequest.setDoctorbill(100);         
         
         else
             billingRequest.setDoctorbill(150);   
    
        Organization org = null;
        for(Network network : business.getNetworkList()){
           // if (enterprise instanceof HospitalEnterprise){
        for(Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()){
           
       
        for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()){
            if (organization instanceof BillingOrganization){
                org = organization;
                break;
            }
        }
        
        if (org!=null){
            org.getWorkQueue().getWorkRequestList().add(billingRequest);
            account.getWorkQueue().getWorkRequestList().add(billingRequest);
            break;
            //System.out.println(doctorRequest);
        }
        }
        //}
        }
        
        
           try {
                
            Email.sendMail("pvidhi107@gmail.com","Final Invoice for "+request.getName1()+" is ready ","Please find below the Doctor's Consulting fee for "+request.getName1()+": $"+testRequiredTxt.getText());
                
             
        } catch (Exception ex) {
            Logger.getLogger(PoliceViewRecordJPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
           
           
            JOptionPane.showMessageDialog(null, "Information sent to Billing");
            
            
            
Logger logger = Logger.getLogger("MyLog");  
      FileHandler fh;  

    try {  

        // This block configure the logger with handler and formatter  
        fh = new FileHandler("D:/MyLogFile.log");  
        logger.addHandler(fh);
        SimpleFormatter formatter = new SimpleFormatter();  
        fh.setFormatter(formatter);  

        // the following statement is used to log any messages  
        logger.info("Request for "+billingRequest.getName1()+"has been sent to Billing by "+account);  

    } catch (SecurityException e) {  
        e.printStackTrace();  
    } catch (IOException e) {  
        e.printStackTrace();  
    } 

    }//GEN-LAST:event_btnPharmacyActionPerformed

    private void labBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_labBtnActionPerformed
        // TODO add your handling code here:


         String message = messageTxt.getText();

         if(message==null||message.equals("")){
       JOptionPane.showMessageDialog(null, "Enter Prescription");
       return;
       }



        LabWorkRequest labRequest = new LabWorkRequest();
        
         labRequest.setMessage(messageTxt.getText());
        labRequest.setId(request.getId());
        labRequest.setSender(account);
        labRequest.setTestResult(messageTxt.getText());
        labRequest.setStatus("Sent to Lab");
        labRequest.setName1(request.getName1());
        labRequest.setAge(request.getAge());
        labRequest.setLocation(request.getLocation());
        labRequest.setGender(request.getGender());
        labRequest.setCloth(request.getCloth());
        labRequest.setFood(request.getFood());
        labRequest.setTreatment(request.getTreatment());
        labRequest.setCriminal(request.getCriminal());
        labRequest.setTesttype(testRequiredTxt.getText());
        labRequest.setClothCost(request.getClothCost());
        labRequest.setFoodCost(request.getFoodCost());
        
        
        

         if(testRequiredTxt.getText().equals("No test Required"))
             labRequest.setDoctorbill(100);         
         
         else
             labRequest.setDoctorbill(150);   
        
        
      
     
              
Organization org = null;
        for(Network network : business.getNetworkList()){
           // if (enterprise instanceof HospitalEnterprise){
        for(Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()){
           
       
        for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()){
            if (organization instanceof LabOrganization){
                org = organization;
                break;
            }
        }
        
        if (org!=null){
            org.getWorkQueue().getWorkRequestList().add(labRequest);
            account.getWorkQueue().getWorkRequestList().add(labRequest);
            break;
            //System.out.println(doctorRequest);
        }
        }
        //}
        }
        
        request.setStatus("Sent to Lab");
        
        
        
           try {
            Email.sendMail("pvidhi107@gmail.com","Lab Test"+testRequiredTxt.getText()+" Required for "+request.getName1(),"Information of "+request.getName1()+"has been added to the queue for Treatment . Please take necessary action");
            
        } catch (Exception ex) {
            Logger.getLogger(PoliceViewRecordJPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
           
           
             JOptionPane.showMessageDialog(null, "Information Sent to Lab");
             
             
             
             
             
             
Logger logger = Logger.getLogger("MyLog");  
      FileHandler fh;  

    try {  

        // This block configure the logger with handler and formatter  
        fh = new FileHandler("D:/MyLogFile.log");  
        logger.addHandler(fh);
        SimpleFormatter formatter = new SimpleFormatter();  
        fh.setFormatter(formatter);  

        // the following statement is used to log any messages  
        logger.info("Request for "+labRequest.getName1()+"has been sent to Lab by "+account);  

    } catch (SecurityException e) {  
        e.printStackTrace();  
    } catch (IOException e) {  
        e.printStackTrace();  
    } 

    }//GEN-LAST:event_labBtnActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       
     userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        DoctorWorkAreaJPanel dwjp = (DoctorWorkAreaJPanel) component;
        dwjp.populateTable();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);       
// TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPharmacy;
    private javax.swing.JLabel enterpriseLabel3;
    private javax.swing.JLabel enterpriseLabel4;
    private javax.swing.JLabel enterpriseLabel5;
    private javax.swing.JLabel enterpriseLabel6;
    private javax.swing.JLabel enterpriseLabel8;
    private javax.swing.JLabel enterpriseLabel9;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JButton labBtn;
    private javax.swing.JTextArea messageTxt;
    private javax.swing.JTextField testRequiredTxt;
    // End of variables declaration//GEN-END:variables
}
