/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.PoliceRole;

import Business.Enterprise.Enterprise;
import Business.Homeless.Homeless;
import Business.Homeless.HomelessDirectory;
import Business.Organization.PoliceOrganization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import userinterface.NGOSupervisorRole.NGOSupervisorWorkAreaJPanel;

/**
 *
 * @author viee
 */
public class AddHomelessPersonJPanel extends javax.swing.JPanel {

     private JPanel userProcessContainer;
    private PoliceOrganization policeOrganization;
    private Enterprise enterprise;
    private UserAccount userAccount;
    private HomelessDirectory homelessDirectory;
    private Homeless homeless;
    /**
     * Creates new form AddHomelessPersonJPanel
     */

    AddHomelessPersonJPanel(JPanel userProcessContainer, HomelessDirectory homelessDirectory) {
        initComponents();
        this.homelessDirectory = homelessDirectory;
        this.userProcessContainer = userProcessContainer;
        populateTable();
        
        addHomelessBtn.setToolTipText("Add a new person to Directory");
        btnUpdate.setToolTipText("Update a Persons Information");
        saveBtn.setToolTipText("Save the Persons Updated Information");
        deleteBtn.setToolTipText("Delete a Existing Persons Information");
//To change body of generated methods, choose Tools | Templates.
    }
    
    public void populateTable(){
            DefaultTableModel dtm = (DefaultTableModel) homelessTbl.getModel();
            dtm.setRowCount(0);
            for(Homeless homeless : homelessDirectory.getHomelessList()){
                Object[] row = new Object[9]; 
                row[0] = homeless;
                row[1] = homeless.getName();
                row[2] = homeless.getAge();
                row[3] = homeless.getLocation();
                row[4] = homeless.getGender();
                row[5] = homeless.isClothingRequired();
                row[6] = homeless.isTreatmentRequired();
                row[7] = homeless.isFoodRequired();
                row[8] = homeless.isCriminalRecord(); 
                 dtm.addRow(row);
            }
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        clothingChk = new javax.swing.JCheckBox();
        treatmentChk = new javax.swing.JCheckBox();
        saveBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        homelessTbl = new javax.swing.JTable();
        btnUpdate = new javax.swing.JButton();
        foodChk = new javax.swing.JCheckBox();
        deleteBtn = new javax.swing.JButton();
        criminalChk = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        addHomelessBtn = new javax.swing.JButton();
        txtName = new javax.swing.JTextField();
        txtAge = new javax.swing.JTextField();
        txtLocation = new javax.swing.JTextField();
        txtGender = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        backJButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(null);

        clothingChk.setBackground(new java.awt.Color(255, 255, 255));
        clothingChk.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        clothingChk.setText("Clothing Required");
        add(clothingChk);
        clothingChk.setBounds(1010, 610, 220, 31);

        treatmentChk.setBackground(new java.awt.Color(255, 255, 255));
        treatmentChk.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        treatmentChk.setText("Treatment Required");
        treatmentChk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                treatmentChkActionPerformed(evt);
            }
        });
        add(treatmentChk);
        treatmentChk.setBounds(1010, 670, 220, 31);

        saveBtn.setBackground(new java.awt.Color(0, 0, 0));
        saveBtn.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        saveBtn.setForeground(new java.awt.Color(255, 255, 255));
        saveBtn.setText("Save Update");
        saveBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 4));
        saveBtn.setEnabled(false);
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });
        add(saveBtn);
        saveBtn.setBounds(110, 190, 200, 40);

        homelessTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Age", "Location", "Gender", "Clothing Required?", "Treatment Required?", "Food Required?", "Is Criminal?"
            }
        ));
        homelessTbl.setSelectionBackground(new java.awt.Color(0, 0, 0));
        homelessTbl.setShowHorizontalLines(false);
        homelessTbl.setShowVerticalLines(false);
        homelessTbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homelessTblMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(homelessTbl);

        add(jScrollPane1);
        jScrollPane1.setBounds(0, 400, 1750, 170);

        btnUpdate.setBackground(new java.awt.Color(0, 0, 0));
        btnUpdate.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnUpdate.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdate.setText("Update Person Details");
        btnUpdate.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 4));
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        add(btnUpdate);
        btnUpdate.setBounds(50, 130, 340, 40);

        foodChk.setBackground(new java.awt.Color(255, 255, 255));
        foodChk.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        foodChk.setText("Food Required");
        add(foodChk);
        foodChk.setBounds(1010, 730, 220, 31);

        deleteBtn.setBackground(new java.awt.Color(0, 0, 0));
        deleteBtn.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        deleteBtn.setForeground(new java.awt.Color(255, 255, 255));
        deleteBtn.setText("Delete Person");
        deleteBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 4));
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });
        add(deleteBtn);
        deleteBtn.setBounds(110, 340, 200, 40);

        criminalChk.setBackground(new java.awt.Color(255, 255, 255));
        criminalChk.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        criminalChk.setText("Criminal Record");
        criminalChk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                criminalChkActionPerformed(evt);
            }
        });
        add(criminalChk);
        criminalChk.setBounds(1010, 790, 220, 31);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Gender:");
        add(jLabel4);
        jLabel4.setBounds(560, 790, 100, 20);

        addHomelessBtn.setBackground(new java.awt.Color(0, 0, 0));
        addHomelessBtn.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        addHomelessBtn.setForeground(new java.awt.Color(255, 255, 255));
        addHomelessBtn.setText("Add Homeless Person");
        addHomelessBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 4));
        addHomelessBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addHomelessBtnActionPerformed(evt);
            }
        });
        add(addHomelessBtn);
        addHomelessBtn.setBounds(770, 850, 310, 37);

        txtName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        add(txtName);
        txtName.setBounds(660, 610, 240, 30);

        txtAge.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtAge.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        add(txtAge);
        txtAge.setBounds(660, 670, 240, 30);

        txtLocation.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtLocation.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        add(txtLocation);
        txtLocation.setBounds(660, 730, 240, 30);

        txtGender.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtGender.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        add(txtGender);
        txtGender.setBounds(660, 790, 240, 30);

        jLabel11.setBackground(new java.awt.Color(204, 204, 204));
        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Manage Homeless Person");
        jLabel11.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 13), new java.awt.Color(102, 102, 102))); // NOI18N
        add(jLabel11);
        jLabel11.setBounds(0, 0, 1750, 80);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("Name:");
        add(jLabel8);
        jLabel8.setBounds(560, 610, 100, 30);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setText("Age:");
        add(jLabel10);
        jLabel10.setBounds(560, 670, 100, 22);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setText("Location:");
        add(jLabel12);
        jLabel12.setBounds(560, 730, 100, 20);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel13.setIcon(new javax.swing.ImageIcon("C:\\Users\\rachi\\Desktop\\Images Project\\homelessmanage.jpg")); // NOI18N
        jLabel13.setText("Request to NGO");
        add(jLabel13);
        jLabel13.setBounds(-10, 0, 2140, 400);

        backJButton.setBackground(new java.awt.Color(0, 0, 0));
        backJButton.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        backJButton.setForeground(new java.awt.Color(255, 255, 255));
        backJButton.setText("<< Back");
        backJButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 4));
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton);
        backJButton.setBounds(20, 840, 120, 40);
    }// </editor-fold>//GEN-END:initComponents

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        
          
         String name1 = txtName.getText();
        int age1 = 0 ;
         String location1 = txtLocation.getText();
         String gender1 = txtGender.getText();
        
         if (name1.equals("") || name1.equals(null))
        {
            JOptionPane.showMessageDialog(null,"Please enter a name");
            return;
        }
         try {
            age1 = Integer.parseInt(txtAge.getText());
        }
        catch(NumberFormatException e)
        {
            JOptionPane.showMessageDialog(null,"Please enter a number for age");
            return;
        }
         if (location1.equals("") || location1.equals(null))
        {
            JOptionPane.showMessageDialog(null,"Please enter a location");
            return;
        }
         
        
        
        
        int selectedRow = homelessTbl.getSelectedRow();

      
        if (selectedRow >= 0) {
            Homeless homeless = (Homeless) homelessTbl.getValueAt(selectedRow, 0);
            String name = txtName.getText();
            Integer age = Integer.parseInt(txtAge.getText());
            String location = txtLocation.getText();
            String gender = txtGender.getText();
            boolean clothingRequired = clothingChk.isSelected();
            boolean shelterRequired = treatmentChk.isSelected();
            boolean treatmentRequired = foodChk.isSelected();
            boolean criminalRecord = criminalChk.isSelected();

            homeless.setName(name);
            homeless.setAge(age);
            homeless.setGender(gender);
            homeless.setLocation(location);
            homeless.setClothingRequired(clothingRequired);
            homeless.setTreatmentRequired(shelterRequired);
            homeless.setFoodRequired(treatmentRequired);
            homeless.setCriminalRecord(criminalRecord);

            JOptionPane.showMessageDialog(null, "Homeless details updated");
            populateTable();

            txtName.setText("");
            txtGender.setText("");
            txtLocation.setText("");
            txtAge.setText("");
            clothingChk.setSelected(false);
            criminalChk.setSelected(false);
            treatmentChk.setSelected(false);
            foodChk.setSelected(false);

            saveBtn.setEnabled(false);
            btnUpdate.setEnabled(true);
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_saveBtnActionPerformed

    private void homelessTblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homelessTblMouseClicked

        //        int i = homelessTbl.getSelectedRow();
        //        TableModel model = homelessTbl.getModel();
        //        idTxt.setText((String) model.getValueAt(i,0));
        //        nameTxt.setText(model.getValueAt(i,2).toString());

    }//GEN-LAST:event_homelessTblMouseClicked

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        
        
        addHomelessBtn.setEnabled(false);
        
        
        
        int selectedRow = homelessTbl.getSelectedRow();
        if (selectedRow<0) {
            JOptionPane.showMessageDialog(null, "Please select row first", "Warning", JOptionPane.WARNING_MESSAGE);
            
        }
        else{
            Homeless homeless = (Homeless)homelessTbl.getValueAt(selectedRow, 0);

            txtName.setText(homeless.getName());
            txtAge.setText(String.valueOf(homeless.getAge()));
            txtLocation.setText(homeless.getLocation());
            txtGender.setText(homeless.getGender());
            clothingChk.setSelected(homeless.isClothingRequired());
            treatmentChk.setSelected(homeless.isTreatmentRequired());
            foodChk.setSelected(homeless.isFoodRequired());
            criminalChk.setSelected(homeless.isCriminalRecord());

            txtName.setEnabled(true);
            txtAge.setEnabled(true);
            txtGender.setEnabled(true);
            txtLocation.setEnabled(true);

            saveBtn.setEnabled(true);
            btnUpdate.setEnabled(false);

        }
        
       
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        int selectedRow = homelessTbl.getSelectedRow();
        if(selectedRow >= 0) {
            int dialogButton = JOptionPane.YES_NO_OPTION;
            int dialogResult = JOptionPane.showConfirmDialog(null, "Would you like to delete account details?", "Warning", dialogButton);
            if(dialogResult == JOptionPane.YES_OPTION){
                Homeless homeless = (Homeless) homelessTbl.getValueAt(selectedRow, 0);
                homelessDirectory.deleteHomeless(homeless);
                populateTable();
                JOptionPane.showMessageDialog(null,"Deleted");
            }
        } 
        else 
        {
           JOptionPane.showMessageDialog(null,"Please select a row");  
        }// TODO add your handling code here:
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void criminalChkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_criminalChkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_criminalChkActionPerformed
       int id = 25;
    private void addHomelessBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addHomelessBtnActionPerformed
          
         String name1 = txtName.getText();
        int age1 = 0 ;
         String location1 = txtLocation.getText();
         String gender1 = txtGender.getText();
        
         if (name1.equals("") || name1.equals(null))
        {
            JOptionPane.showMessageDialog(null,"Please enter a name");
            return;
        }
         try {
            age1 = Integer.parseInt(txtAge.getText());
        }
        catch(NumberFormatException e)
        {
            JOptionPane.showMessageDialog(null,"Please enter a number for age");
            return;
        }
         if (location1.equals("") || location1.equals(null))
        {
            JOptionPane.showMessageDialog(null,"Please enter a location");
            return;
        }
        
//         if (!txtGender.getText().equals("Male") || !(gender1.equalsIgnoreCase("Female")))
//        {
//            JOptionPane.showMessageDialog(null,"Please enter a proper Gender");
//            return;
//        }
//        
//        
        
       
        
        id = id +1;
        boolean clothingRequired = false;
        boolean shelterRequired = false;
        boolean foodRequired = false;
        boolean criminalRecord = false;
        String name = txtName.getText();
        Integer age = Integer.parseInt(txtAge.getText());
        String location = txtLocation.getText();
        String gender = txtGender.getText();
        if(clothingChk.isSelected()){
            clothingRequired = true;
        }
        
        if(treatmentChk.isSelected()){
            shelterRequired = true;
        }
        
        if(foodChk.isSelected()){
            foodRequired = true;
        }
        
        if(criminalChk.isSelected()){
            criminalRecord = true;
        }
        
//        Homeless homeless = homelessDirectory.createHomeless();
//        
//        int id =homeless.getC();
//        homeless.setId(id);
//        
        
        Homeless homeless = homelessDirectory.createHomeless();
         homeless.setId(id);
        homeless.setName(name);
        homeless.setGender(gender);
        homeless.setAge(age);
        homeless.setLocation(location);
        homeless.setClothingRequired(clothingRequired);
        homeless.setTreatmentRequired(shelterRequired);
        homeless.setFoodRequired(foodRequired);
        homeless.setCriminalRecord(criminalRecord);
        
        JOptionPane.showMessageDialog(null, "Homeless Person Added!");
        populateTable();

        txtName.setText("");
        txtGender.setText("");
        txtLocation.setText("");
        txtAge.setText("");
        clothingChk.setSelected(false);
        criminalChk.setSelected(false);
        treatmentChk.setSelected(false);
        foodChk.setSelected(false);
        //        AddHomelessPersonJPanel addpersonpanel = new AddHomelessPersonJPanel(userProcessContainer,homelessDirectory);
        //      userProcessContainer.add("AddpersonJPanel", addpersonpanel);
        //        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        //        layout.next(userProcessContainer);        // TODO add your handling code here:

       
    }//GEN-LAST:event_addHomelessBtnActionPerformed

    private void treatmentChkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_treatmentChkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_treatmentChkActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        PoliceViewRecordJPanel dwjp = (PoliceViewRecordJPanel) component;
        dwjp.populateTable();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addHomelessBtn;
    private javax.swing.JButton backJButton;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JCheckBox clothingChk;
    private javax.swing.JCheckBox criminalChk;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JCheckBox foodChk;
    private javax.swing.JTable homelessTbl;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton saveBtn;
    private javax.swing.JCheckBox treatmentChk;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtGender;
    private javax.swing.JTextField txtLocation;
    private javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables
}
