/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.PoliceRole;

import Business.Enterprise.Enterprise;
import Business.Homeless.Homeless;
import Business.Homeless.HomelessDirectory;
import Business.Organization.NGOOrganization;
import Business.Organization.Organization;
import Business.Organization.PoliceOrganization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.NGOWorkRequest;
import Business.email.Email;
import java.awt.CardLayout;
import java.io.IOException;
import java.util.HashSet;
import java.util.logging.FileHandler;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.logging.SimpleFormatter;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author viee
 */
public class PoliceViewRecordJPanel extends javax.swing.JPanel {
    
    private JPanel userProcessContainer;
    private PoliceOrganization policeOrganization;
    private Enterprise enterprise;
    private UserAccount userAccount;
    private HomelessDirectory homelessDirectory;
    private Homeless homeless;
    /**
     * Creates new form PoliceViewJPanel
     */
    public PoliceViewRecordJPanel(JPanel userProcessContainer, UserAccount account, PoliceOrganization policeOrganization, Enterprise enterprise,HomelessDirectory homelessDirectory){
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = account;
        this.policeOrganization = policeOrganization;
        this.enterprise = enterprise;
        this.homelessDirectory = homelessDirectory;
        
        populateTable();
        requestTestJButton.setToolTipText("Validate the Person details and send to NGO for essentials");
        addHomelessBtn.setToolTipText("Add a new Homeless Person to the list");
       
    }
    
    public void populateTable(){
            DefaultTableModel dtm = (DefaultTableModel) homelessTbl.getModel();
            dtm.setRowCount(0);
            for(Homeless homeless : homelessDirectory.getHomelessList()){
                Object[] row = new Object[9]; 
                row[0] = homeless;
                row[1] = homeless.getName();
                row[2] = homeless.getAge();
                row[3] = homeless.getLocation();
                row[4] = homeless.getGender();
                row[5] = homeless.isClothingRequired();
                row[6] = homeless.isTreatmentRequired();
                row[7] = homeless.isFoodRequired();
                row[8] = homeless.isCriminalRecord(); 
                 dtm.addRow(row);
            }
        }
  
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        homelessTbl = new javax.swing.JTable();
        idTxt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        nameTxt = new javax.swing.JTextField();
        messageJTextField = new javax.swing.JTextField();
        requestTestJButton = new javax.swing.JButton();
        clothTxt = new javax.swing.JTextField();
        treatmentTxt = new javax.swing.JTextField();
        foodTxt = new javax.swing.JTextField();
        criminalTxt = new javax.swing.JTextField();
        addHomelessBtn = new javax.swing.JButton();
        ageTxt = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        genderTxt = new javax.swing.JTextField();
        locationTxt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(null);

        homelessTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Age", "Location", "Gender", "Clothing Required?", "Treatment Required?", "Food Required?", "Is Criminal?"
            }
        ));
        homelessTbl.setGridColor(new java.awt.Color(255, 255, 255));
        homelessTbl.setSelectionBackground(new java.awt.Color(0, 0, 0));
        homelessTbl.setShowHorizontalLines(false);
        homelessTbl.setShowVerticalLines(false);
        homelessTbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homelessTblMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(homelessTbl);

        add(jScrollPane1);
        jScrollPane1.setBounds(0, 80, 1750, 150);

        idTxt.setEditable(false);
        idTxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        idTxt.setEnabled(false);
        idTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idTxtActionPerformed(evt);
            }
        });
        add(idTxt);
        idTxt.setBounds(370, 630, 190, 40);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Message");
        add(jLabel3);
        jLabel3.setBounds(280, 740, 80, 22);

        nameTxt.setEditable(false);
        nameTxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        nameTxt.setEnabled(false);
        nameTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameTxtActionPerformed(evt);
            }
        });
        add(nameTxt);
        nameTxt.setBounds(370, 680, 190, 40);

        messageJTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        messageJTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                messageJTextFieldActionPerformed(evt);
            }
        });
        add(messageJTextField);
        messageJTextField.setBounds(370, 730, 190, 40);

        requestTestJButton.setBackground(new java.awt.Color(0, 0, 0));
        requestTestJButton.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        requestTestJButton.setForeground(new java.awt.Color(255, 255, 255));
        requestTestJButton.setText("Send To NGO");
        requestTestJButton.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        requestTestJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requestTestJButtonActionPerformed(evt);
            }
        });
        add(requestTestJButton);
        requestTestJButton.setBounds(790, 850, 170, 33);

        clothTxt.setEditable(false);
        clothTxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        clothTxt.setEnabled(false);
        add(clothTxt);
        clothTxt.setBounds(870, 630, 210, 40);

        treatmentTxt.setEditable(false);
        treatmentTxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        treatmentTxt.setEnabled(false);
        add(treatmentTxt);
        treatmentTxt.setBounds(870, 680, 210, 40);

        foodTxt.setEditable(false);
        foodTxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        foodTxt.setEnabled(false);
        add(foodTxt);
        foodTxt.setBounds(870, 730, 210, 40);

        criminalTxt.setEditable(false);
        criminalTxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        criminalTxt.setEnabled(false);
        criminalTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                criminalTxtActionPerformed(evt);
            }
        });
        add(criminalTxt);
        criminalTxt.setBounds(1340, 630, 210, 40);

        addHomelessBtn.setBackground(new java.awt.Color(0, 0, 0));
        addHomelessBtn.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        addHomelessBtn.setForeground(new java.awt.Color(255, 255, 255));
        addHomelessBtn.setText("Manage Homeless Person");
        addHomelessBtn.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        addHomelessBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addHomelessBtnActionPerformed(evt);
            }
        });
        add(addHomelessBtn);
        addHomelessBtn.setBounds(700, 250, 330, 40);

        ageTxt.setEditable(false);
        ageTxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        ageTxt.setEnabled(false);
        ageTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ageTxtActionPerformed(evt);
            }
        });
        add(ageTxt);
        ageTxt.setBounds(870, 780, 210, 40);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setIcon(new javax.swing.ImageIcon("C:\\Users\\rachi\\Desktop\\Images Project\\policeworkarea.jpeg")); // NOI18N
        jLabel11.setText("Request to NGO");
        jLabel11.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 13), new java.awt.Color(102, 102, 102))); // NOI18N
        add(jLabel11);
        jLabel11.setBounds(0, 230, 1750, 370);

        genderTxt.setEditable(false);
        genderTxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        genderTxt.setEnabled(false);
        genderTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genderTxtActionPerformed(evt);
            }
        });
        add(genderTxt);
        genderTxt.setBounds(1340, 730, 210, 40);

        locationTxt.setEditable(false);
        locationTxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        locationTxt.setEnabled(false);
        locationTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                locationTxtActionPerformed(evt);
            }
        });
        add(locationTxt);
        locationTxt.setBounds(1340, 680, 210, 40);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Age");
        add(jLabel4);
        jLabel4.setBounds(650, 790, 50, 20);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Name");
        add(jLabel5);
        jLabel5.setBounds(280, 690, 60, 22);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("ID");
        add(jLabel6);
        jLabel6.setBounds(280, 640, 50, 22);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Gender");
        add(jLabel7);
        jLabel7.setBounds(1150, 740, 170, 20);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("Treatment Required");
        add(jLabel8);
        jLabel8.setBounds(650, 690, 190, 20);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setText("Food Required");
        add(jLabel9);
        jLabel9.setBounds(650, 740, 170, 20);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setText("Clothing Required");
        add(jLabel10);
        jLabel10.setBounds(650, 640, 170, 22);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setText("Criminal Record");
        add(jLabel12);
        jLabel12.setBounds(1150, 640, 170, 20);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setText("Current Location");
        add(jLabel13);
        jLabel13.setBounds(1150, 690, 170, 20);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText(" Homeless Person Request");
        jLabel14.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 13), new java.awt.Color(102, 102, 102))); // NOI18N
        add(jLabel14);
        jLabel14.setBounds(0, 0, 1750, 80);
    }// </editor-fold>//GEN-END:initComponents

    private void homelessTblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homelessTblMouseClicked

        int i = homelessTbl.getSelectedRow();
        TableModel model = homelessTbl.getModel();
        idTxt.setText(model.getValueAt(i,0).toString());
        nameTxt.setText(model.getValueAt(i,1).toString());
        
        clothTxt.setText(model.getValueAt(i,5).toString());
        treatmentTxt.setText(model.getValueAt(i,6).toString());
        foodTxt.setText(model.getValueAt(i,7).toString());
        criminalTxt.setText(model.getValueAt(i,8).toString());
        ageTxt.setText(model.getValueAt(i,2).toString());
        locationTxt.setText(model.getValueAt(i,3).toString());
        genderTxt.setText(model.getValueAt(i,4).toString());
        

    }//GEN-LAST:event_homelessTblMouseClicked

    private void idTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idTxtActionPerformed

    private void nameTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameTxtActionPerformed

    private void requestTestJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requestTestJButtonActionPerformed

        

      int selectedRow = homelessTbl.getSelectedRow();

        if (selectedRow < 0){
            JOptionPane.showMessageDialog(null, "Please Select a Row First");
            return;
        }
        
        
        if (criminalTxt.getText().equals("true")){
            JOptionPane.showMessageDialog(null, "Shelter Cannot be Provided : This person is a criminal");
            return;
        }
        
        String message = messageJTextField.getText();
        String name1 = nameTxt.getText();
        String id = String.valueOf(idTxt.getText());
        String iscloth = clothTxt.getText();
        String isShelter = treatmentTxt.getText();
        String isFood = foodTxt.getText();
        String isCriminal = criminalTxt.getText();
        int age = Integer.parseInt(ageTxt.getText());
        String location = locationTxt.getText();
        String gender = genderTxt.getText();
      
        
        
      
        
       if(message==null||message.equals("")){
       JOptionPane.showMessageDialog(null, "Enter Request Message");
       } 
       
       else{
           
             NGOWorkRequest request = new NGOWorkRequest();
        request.setMessage(message);
        request.setSender(userAccount);
        request.setStatus("Sent to NGO");
        request.setName1(name1);
        request.setCloth(Boolean. valueOf(iscloth) );
        request.setTreatment(Boolean. valueOf(isShelter) );
        request.setFood(Boolean. valueOf(isFood) );
        request.setCriminal(Boolean. valueOf(isCriminal) );
        request.setAge(age);
        request.setLocation(location);
        request.setGender(gender);
        //String id = idTxt.getText();
        request.setId(id);
        
         JOptionPane.showMessageDialog(null, "Homeless Request Sent to NGO");
         
       
                
            

        
     
     Organization org = null;
        for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()){
            if (organization instanceof NGOOrganization){
                org = organization;
                break;
            }
        }
        if (org!=null){
            org.getWorkQueue().getWorkRequestList().add(request);
            userAccount.getWorkQueue().getWorkRequestList().add(request);
        }
               try {
            Email.sendMail("pvidhi107@gmail.com","New Person's Request Has Been Sent","Information of "+request.getName1()+"has been added to the queue. Please take necessary action");
            
        } catch (Exception ex) {
            Logger.getLogger(PoliceViewRecordJPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
               
               
               int selectedRow1 = homelessTbl.getSelectedRow();
               Homeless homeless = (Homeless) homelessTbl.getValueAt(selectedRow1, 0);
               homelessDirectory.deleteHomeless(homeless);
               populateTable();
               
               
                     
Logger logger = Logger.getLogger("MyLog");  
      FileHandler fh;  

    try {  

        // This block configure the logger with handler and formatter  
        fh = new FileHandler("D:/MyLogFile.log");  
        logger.addHandler(fh);
        SimpleFormatter formatter = new SimpleFormatter();  
        fh.setFormatter(formatter);  

        // the following statement is used to log any messages  
        logger.info("Request for "+request.getName1()+"has been sent to NGO by "+userAccount);  

    } catch (SecurityException e) {  
        e.printStackTrace();  
    } catch (IOException e) {  
        e.printStackTrace();  
    } 
       
        
       } 
       
       
 
       
    }//GEN-LAST:event_requestTestJButtonActionPerformed

    private void criminalTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_criminalTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_criminalTxtActionPerformed

    private void addHomelessBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addHomelessBtnActionPerformed
        AddHomelessPersonJPanel addHomeless = new AddHomelessPersonJPanel(userProcessContainer,homelessDirectory);
        userProcessContainer.add("AddHomelessPersonJPanel", addHomeless);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);         // TODO add your handling code here:
    }//GEN-LAST:event_addHomelessBtnActionPerformed

    private void ageTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ageTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ageTxtActionPerformed

    private void genderTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genderTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_genderTxtActionPerformed

    private void locationTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_locationTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_locationTxtActionPerformed

    private void messageJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_messageJTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_messageJTextFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addHomelessBtn;
    private javax.swing.JTextField ageTxt;
    private javax.swing.JTextField clothTxt;
    private javax.swing.JTextField criminalTxt;
    private javax.swing.JTextField foodTxt;
    private javax.swing.JTextField genderTxt;
    private javax.swing.JTable homelessTbl;
    private javax.swing.JTextField idTxt;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField locationTxt;
    private javax.swing.JTextField messageJTextField;
    private javax.swing.JTextField nameTxt;
    private javax.swing.JButton requestTestJButton;
    private javax.swing.JTextField treatmentTxt;
    // End of variables declaration//GEN-END:variables
}
